
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbahnltlztuwocqlhgxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYWhubHRsenR1d29jcWxoZ3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTUyMzgsImV4cCI6MjA1Nzk3MTIzOH0.sNOIRR6MW_X-n31hyidfqBrWOIP1WRoDFYCDeRHEQZ0";

// Define extended Database type with tables
interface DatabaseWithTables extends Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          account_type: string;
          area_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          account_type?: string;
          area_code?: string | null;
        };
        Update: {
          username?: string;
          account_type?: string;
          area_code?: string | null;
        };
      };
      complaints: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string;
          location: string;
          pincode: string;
          image_url: string | null;
          after_image_url: string | null;
          status: string;
          area_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description: string;
          location: string;
          pincode: string;
          image_url?: string | null;
          after_image_url?: string | null;
          status?: string;
          area_code?: string | null;
        };
        Update: {
          title?: string;
          description?: string;
          location?: string;
          pincode?: string;
          image_url?: string | null;
          after_image_url?: string | null;
          status?: string;
          area_code?: string | null;
        };
      };
    };
    Views: Database['public']['Views'];
    Functions: Database['public']['Functions'];
    Enums: Database['public']['Enums'];
    CompositeTypes: Database['public']['CompositeTypes'];
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<DatabaseWithTables>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
